name: CI

on: [push]

jobs:
  build:

    runs-on: node:10

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Test keys $ACTIONS_DEPLOY_KEY
        echo Add other actions to build,
        echo test, and deploy your project.
