name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v1
      #- uses: actions/setup-node@v1
      #  with:
      #    node-version: '10.x'
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        run: |
          mkdir public
          echo 'Hooray!' > public/index.html
          ls public
          mkdir /root/.ssh
          ssh-keyscan -t rsa github.com > "/root/.ssh/known_hosts"
          echo "${SSH_DEPLOY_KEY}" > "/root/.ssh/id_rsa"
          chmod 400 "/root/.ssh/id_rsa"
          cd public
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          export remote_repo="git@github.com:${PUBLISH_REPOSITORY}.git"
          git init
          git checkout --orphan gh-pages
          git remote rm origin || true
          git remote add origin "${remote_repo}"
          git add --all
          git push origin -f
